### ISSUE TITLE
nodejs `req` object vs fetch's `Request` instance

### ISSUE THREAD

**Issue by amithm7** [serverless-dns/serverless-dns#34]
Regression introduced in https://github.com/serverless-dns/serverless-dns/commit/a850e529cecb584ca2ea3d38b20a914af23c132e

Error stack:

```log
  const ua = req.headers.get("User-Agent")
                         ^
TypeError: req.headers.get is not a function
    at fromBrowser (file:///node-dir/src/helpers/util.js:42:26)
    at Module.corsHeadersIfNeeded (file:///node-dir/src/helpers/util.js:68:11)
    at Http2SecureServer.serveHTTPS (file:///node-dir/src/server.js:393:50)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

https://github.com/serverless-dns/serverless-dns/blob/bbbbb3d7f7bbb5010f144191181dceee99311c35/src/helpers/util.js#L42

This is being called with NodeJS http `req` passed. From here:

https://github.com/serverless-dns/serverless-dns/blob/bbbbb3d7f7bbb5010f144191181dceee99311c35/src/server.js#L393

Unlike fetch's `Request` instance, this an object and `ua` can be got like this:

```js
const ua = req.headers["user-agent"];
```

This requires 2 diff. functions ? and maybe JSDoc for type `Http2ServerRequest` (nodejs: h2) vs `Request` (fetch). Like this:
https://github.com/serverless-dns/serverless-dns/blob/bbbbb3d7f7bbb5010f144191181dceee99311c35/src/server.js#L374-L379

**Comment by ignoramous** [comment]
Yikes. TypeScript...

**Comment by ignoramous** [comment]
So: Nodejs Request obj is not the same as Web API Request obj... TypeScript is a pipe dream... for now, changing the util func API signatures to explicitly *accept* the properties they need (for ex, UA string instead of the Request obj in case of `util.corsHeadersIfNeeded(ua)`) might be good intermediate soln?
